### PR TITLE
ros-canopen: adding can-msgs, socketcan-interface and socketcan-bridge

### PR DESCRIPTION
**Pull request by DasRoteSkelett**

### CODE REVIEW

**Comment by bulwahn** [comment]
Sorry for the late response. I was quite busy lately.

I tested `bitbake can-msgs socketcan-bridge socketcan-interface` on this build configuration:
```
Build Configuration:
BB_VERSION           = "1.35.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "i586-oe-linux"
MACHINE              = "qemux86"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "m32 i586"
TARGET_FPU           = ""
meta                 = "master:addf309165059a113a6d02ea5fb29a0f495c1485"
meta-oe              
meta-multimedia      
meta-python          = "master:e08670d4362b57373557fbe6b31cbffffa465acc"
meta-ros             = "DasRoteSkelett-kinetic-experimental-v3-alpha1:aed2202182dff2b00809406ce38c72681e06e16b"
```

`bitbake socketcan-interface` failed with:
```
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/socketcan-interface/0.7.6-r0/ros_canopen-0.7.6/socketcan_interface/include/socketcan_interface/socketcan.h: In member function 'virtual bool can::SocketCANInterface::enqueue(const can::Frame&)':
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/socketcan-interface/0.7.6-r0/ros_canopen-0.7.6/socketcan_interface/include/socketcan_interface/interface.h:202:96: error: 'cout' is not a member of 'std'
|  #define LOG(log) { boost::mutex::scoped_lock _cout_lock(_cout_wrapper::get_cout_mutex()); std::cout << log << std::endl; }
|                                                                                                 ^
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/socketcan-interface/0.7.6-r0/ros_canopen-0.7.6/socketcan_interface/include/socketcan_interface/socketcan.h:183:13: note: in expansion of macro 'LOG'
|              LOG("FAILED " << ec);
|              ^
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/socketcan-interface/0.7.6-r0/ros_canopen-0.7.6/socketcan_interface/include/socketcan_interface/interface.h:202:96: note: suggested alternative: 'count'
```

**Comment by bulwahn** [comment]
I had a quick look at the sources; it is probably related to the specific boost version we are using in openembedded-core on the current master. With older versions of boost (that the other builds rely on), iostream is included by the boost dependencies in the header files; with the version we use, it is not included anymore and hence leads to this error.

**Comment by bulwahn** [comment]
I have a patch that addresses the issue, I will provide that patch upstream to the `ros_canopen` repository and then add another patch to this pull request. Once, that is done, I will merge it.

**Comment by DasRoteSkelett** [comment]
Hi Lukas, 

thanks for the feedback. I am running rocko here, so could be, that boost is the issue here, since it compiles and runs fine here. 

Regarding this PR and the others: I ran into some other issues, added and needed to modify other recipes (for example joint_state_publisher). So, without wanting to put pressure on you, if the merges take a month, if they are merged at all, that is too slow for me, I would then rather work on my fork, which would be a bit of a pitty, since I really would not mind to give back... 

Regards,

   Matthias

**Comment by bulwahn** [comment]
Hi Matthias,

I think it will be the usual situation that you find something and need to fix something quickly and you have some patches that are not yet merged. For sure, a pending commit for six week was really unexpected (also for me) and for simple things, I am usually a bit quicker.
This pull request is merged, and I actually extended it and cleaned it up.
I would propose to simply open the pull request once you find the commits are good from your side and then one-by-one I will be reviewing and testing them. Once, they are merged, you can always simply rebase your branch and then the already merged commits will be simply dropped. By the way, of course, my repository is not actually being intended to be the central fork for long, but I have plans to put the kinetic branch in the same repository as the indigo branch, but that will probably need some time around Christmas to get the open technical steps on indigo done before moving the kinetic branch into another repository.

Best regards,
Lukas

**Pull request merged**
